### ISSUE TITLE
Inefficiency in Expression class

### ISSUE THREAD

**Issue by ArashPartow** [cigani/NonLinearSolver#1]
There seems to be an extremely inefficient **_'use'_** of Exprtk in the following method: Expression::evaluate

https://github.com/cigani/NonLinearSolver/blob/master/code/Expression.cpp#L39

Instead of compiling the expression from scratch every time you want to evaluate it, why not compile it only **ONCE** during the constructor of the Expression class. That way you'll only need to evaluate the expression in the Expression::evaluate method and nothing else.

So to sum up:

1. In the header of Expression add the following members:

```
expression_t expression_;
double x_,y_,z_;
```

2. In the constructor compile the expression:
```

Expression::Expression(const std::string &eq)
: equation(eq),
  x_(0.0),y_(0.0),z_(0.0)
{
   equation = eq;

   symbol_table_t symbol_table;
   symbol_table.add_variable("x", x_);
   symbol_table.add_variable("y", y_);
   symbol_table.add_variable("z", z_);
   symbol_table.add_constants();

   expression_.register_symbol_table(symbol_table);

   parser_t parser;
   if (!parser.compile(equation, expression_))
   {
     // error... throw an exception or perform some
     // kind of error handling.
   }
}
```

3. In evaluate, you now only need to update the variable(s) and evaluate the expression

```
double Expression::evaluate(double& value)
{
    x_ = value;
    return expression.value();
}

double Expression::evaluate(std::vector<double> &value)
{
   switch (value.size())
   {
      case 3 : z_ = value[2];
      case 2 : y_ = value[1];
      case 1 : x_ = value[0];
   }

   return expression.value();
}

```

**Comment by cigani** [comment]
Thanks a lot for this. We looked at this problem several times but were unable to solve it properly. Sadly we ran out of time and had to accept the inefficient solution we did construct. I'll add your suggested fixes asap. Thanks again.

**Comment by ArashPartow** [comment]
I missed the fact that you were copying the Expression instances around. That's ok though, there is a minor change that needs to be made in order to preserve the references to the variables during the copy constructor or assignment operator invocations of the Expression class.

There's two variations of the modification depending on whether you're using C++11 or later or C++03.


C++11 expression wrapper:
https://gist.github.com/anonymous/e4db504639946e6ab4506c35c68a1d51


C++03 expression wrapper:
https://gist.github.com/anonymous/262b27c12d37f98a42da57c0b61693ed


Expected output for both:
https://gist.github.com/anonymous/a6dafda5120fd7ea0e1b8f90b599b22d

------

Give it a go and let me know if it works for you.

**Comment by cigani** [comment]
Thanks again for your help. I'll be implementing this asap
